sudo: required
services:
  - docker

before_install:
  - docker build -t padronlv/docker-react -f Dockerfile.dev .

script:
  - docker container run -e CI=true padronlv/docker-react npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket-name: "elasticbeanstalk-eu-central-1-189597434021"
  bucket-path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY