sudo: required
services:
  - docker

before_install:
  - docker build -t padronlv/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker container run -e CI=true padronlv/react-test npm run test

after_success:
  - docker build -t padronlv/multi-client ./client
  - docker build -t padronlv/multi-nginx ./nginx
  - docker build -t padronlv/multi-server ./server
  - docker build -t padronlv/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push padronlv/multi-client
  - docker push padronlv/multi-nginx
  - docker push padronlv/multi-server
  - docker push padronlv/multi-worker


deploy:
  edge: true
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket-name: "elasticbeanstalk-eu-central-1-189597434021"
  bucket-path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY